"""
LLM-based Task Synthesis: Use LLM to generate tasks from exploration paths.

PHASE USAGE: Phase 2 (Task Synthesis)

PURPOSE:
- Read exploration paths (screens, actions, transitions)
- Use LLM to understand and synthesize user tasks
- Generate task descriptions and steps
- NO complex algorithms - let LLM do the work

ALIGNED WITH PROFESSOR'S FEEDBACK:
- "LLM reads paths and creates task descriptions"
- "No grounding needed in Phase 2"
- Simple and straightforward approach

USAGE:
    synthesizer = LLMTaskSynthesizer(llm_provider="anthropic")
    tasks = await synthesizer.synthesize_tasks(exploration_result)
"""

import json
import logging
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, asdict
from pathlib import Path

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

from exploration.schema import Screen, ExplorationResult
from utils.env import env as env_config

logger = logging.getLogger(__name__)


@dataclass
class TaskStep:
    """A single step in a task."""
    step_number: int
    description: str
    screen_id: Optional[str] = None
    action_id: Optional[str] = None


@dataclass
class SynthesizedTask:
    """A task generated by LLM."""
    task_id: str
    name: str
    description: str
    steps: List[TaskStep]
    confidence: float = 1.0
    category: str = "general"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "name": self.name,
            "description": self.description,
            "steps": [asdict(step) for step in self.steps],
            "confidence": self.confidence,
            "category": self.category
        }


class LLMTaskSynthesizer:
    """
    LLM-based task synthesizer.

    Uses LLM (Claude or GPT-4) to read exploration data and generate
    realistic user tasks with descriptions.

    This is the NEW approach aligned with Professor Vũ's feedback:
    - Phase 2: LLM reads paths → generates task descriptions
    - No complex algorithms, no grounding
    - Simple and effective
    """

    def __init__(
        self,
        llm_provider: str = "anthropic",
        model: Optional[str] = None,
        api_key: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 4000
    ):
        """
        Initialize LLM task synthesizer.

        Args:
            llm_provider: "anthropic" or "openai"
            model: Model name (defaults: claude-3-5-sonnet or gpt-4)
            api_key: API key (auto-loads from env if None)
            temperature: LLM temperature (0.0-1.0)
            max_tokens: Max tokens in response
        """
        self.llm_provider = llm_provider.lower()
        self.temperature = temperature
        self.max_tokens = max_tokens

        # Initialize LLM client
        if self.llm_provider == "anthropic":
            if not ANTHROPIC_AVAILABLE:
                raise ImportError("anthropic package not installed. Run: pip install anthropic")

            api_key = api_key or env_config.get("ANTHROPIC_API_KEY")
            if not api_key:
                raise ValueError("ANTHROPIC_API_KEY not found in environment")

            self.client = anthropic.Anthropic(api_key=api_key)
            self.model = model or "claude-3-5-sonnet-20241022"

        elif self.llm_provider == "openai":
            if not OPENAI_AVAILABLE:
                raise ImportError("openai package not installed. Run: pip install openai")

            api_key = api_key or env_config.get("OPENAI_API_KEY")
            if not api_key:
                raise ValueError("OPENAI_API_KEY not found in environment")

            self.client = openai.OpenAI(api_key=api_key)
            self.model = model or "gpt-4-turbo-preview"

        else:
            raise ValueError(f"Unsupported LLM provider: {llm_provider}")

        logger.info(f"Initialized LLMTaskSynthesizer with {self.llm_provider} ({self.model})")

    def _format_exploration_data(self, exploration_result: ExplorationResult) -> str:
        """
        Format exploration data into a readable text for LLM.

        Args:
            exploration_result: Exploration result from Phase 1

        Returns:
            Formatted text describing the exploration
        """
        screens = list(exploration_result.screens.values())
        actions = list(exploration_result.actions.values())
        transitions = exploration_result.transitions

        output = []
        output.append("# Website Exploration Data\n")
        output.append(f"Start URL: {exploration_result.start_url}\n")
        output.append(f"Total Screens: {len(screens)}")
        output.append(f"Total Actions: {len(actions)}")
        output.append(f"Total Transitions: {len(transitions)}\n")

        # Group actions by screen
        screen_actions = {}
        for action in actions:
            screen_id = action.meta.get("source_screen_id", "unknown")
            if screen_id not in screen_actions:
                screen_actions[screen_id] = []
            screen_actions[screen_id].append(action)

        # Describe each screen and its actions
        output.append("\n## Screens and Actions\n")
        for i, screen in enumerate(screens[:20], 1):  # Limit to first 20 screens
            output.append(f"\n### Screen {i}: {screen.screen_id}")
            output.append(f"URL: {screen.url}")
            output.append(f"Type: {screen.screen_type.value if hasattr(screen, 'screen_type') else 'unknown'}")

            # Add semantic summary if available
            if hasattr(screen, 'semantic_summary') and screen.semantic_summary:
                output.append(f"Summary: {screen.semantic_summary[:200]}")

            # Add visible text snippet
            if screen.visible_text:
                text_snippet = screen.visible_text[:300].replace('\n', ' ').strip()
                output.append(f"Visible text: {text_snippet}...")

            # List actions from this screen
            screen_action_list = screen_actions.get(screen.screen_id, [])
            if screen_action_list:
                output.append(f"\nActions available ({len(screen_action_list)}):")
                for action in screen_action_list[:10]:  # Limit to 10 actions per screen
                    if hasattr(action, 'semantic') and action.semantic:
                        semantic = action.semantic
                        desc = (semantic.description if hasattr(semantic, 'description')
                               else str(semantic))
                        output.append(f"  - {desc[:100]}")

        # Add some transitions to show flow
        if transitions:
            output.append("\n## Example Transitions (User Flows)\n")
            for i, trans in enumerate(transitions[:15], 1):  # Show first 15 transitions
                from_screen = exploration_result.screens.get(trans.from_screen_id)
                to_screen = exploration_result.screens.get(trans.to_screen_id)

                from_url = from_screen.url if from_screen else "unknown"
                to_url = to_screen.url if to_screen else "unknown"

                action_desc = trans.action_semantic.description if hasattr(trans.action_semantic, 'description') else "action"

                output.append(f"{i}. {from_url} --[{action_desc}]--> {to_url}")

        return "\n".join(output)

    def _build_prompt(self, exploration_data: str) -> str:
        """
        Build prompt for LLM to synthesize tasks.

        Args:
            exploration_data: Formatted exploration data

        Returns:
            Prompt string
        """
        prompt = f"""You are an expert at understanding web application user workflows. You have been given data from an automated exploration of a website. Your task is to synthesize realistic user tasks that someone might want to accomplish on this website.

{exploration_data}

Based on this exploration data, please identify and describe the main user tasks that can be accomplished on this website.

For each task:
1. Give it a clear, concise name
2. Write a description of what the user wants to accomplish
3. Break it down into step-by-step instructions
4. Categorize the task (e.g., "search", "browse", "purchase", "account", "content")

Focus on:
- Common, realistic user goals (not just technical actions)
- Tasks that have clear starting and ending points
- Tasks that users would actually want to do
- Multi-step workflows, not just single actions

Output your response as a JSON array with this structure:
```json
[
  {{
    "name": "Task name",
    "description": "What the user wants to accomplish",
    "category": "category name",
    "steps": [
      "Step 1 description",
      "Step 2 description",
      ...
    ]
  }},
  ...
]
```

Generate 5-15 distinct tasks. Focus on quality over quantity."""

        return prompt

    def _call_llm(self, prompt: str) -> str:
        """
        Call LLM with the prompt.

        Args:
            prompt: Prompt string

        Returns:
            LLM response text
        """
        logger.info(f"Calling {self.llm_provider} LLM...")

        try:
            if self.llm_provider == "anthropic":
                message = self.client.messages.create(
                    model=self.model,
                    max_tokens=self.max_tokens,
                    temperature=self.temperature,
                    messages=[
                        {"role": "user", "content": prompt}
                    ]
                )
                response = message.content[0].text

            elif self.llm_provider == "openai":
                completion = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "user", "content": prompt}
                    ],
                    temperature=self.temperature,
                    max_tokens=self.max_tokens
                )
                response = completion.choices[0].message.content

            else:
                raise ValueError(f"Unsupported provider: {self.llm_provider}")

            logger.info(f"Received response from {self.llm_provider}")
            return response

        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            raise

    def _parse_llm_response(self, response: str) -> List[Dict[str, Any]]:
        """
        Parse LLM response to extract tasks.

        Args:
            response: Raw LLM response

        Returns:
            List of task dictionaries
        """
        # Extract JSON from response (might be wrapped in markdown code blocks)
        response = response.strip()

        # Remove markdown code blocks if present
        if "```json" in response:
            start = response.find("```json") + 7
            end = response.find("```", start)
            response = response[start:end].strip()
        elif "```" in response:
            start = response.find("```") + 3
            end = response.find("```", start)
            response = response[start:end].strip()

        # Parse JSON
        try:
            tasks_data = json.loads(response)

            if not isinstance(tasks_data, list):
                logger.warning("LLM response is not a list, wrapping it")
                tasks_data = [tasks_data]

            return tasks_data

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM response as JSON: {e}")
            logger.debug(f"Response was: {response[:500]}")
            return []

    def synthesize_tasks(self, exploration_result: ExplorationResult) -> List[SynthesizedTask]:
        """
        Synthesize tasks from exploration result using LLM.

        This is the main method aligned with Professor Vũ's feedback:
        - LLM reads exploration paths
        - LLM generates task descriptions
        - Simple and straightforward

        Args:
            exploration_result: Result from Phase 1 exploration

        Returns:
            List of synthesized tasks
        """
        logger.info("Starting LLM-based task synthesis...")

        # 1. Format exploration data for LLM
        exploration_data = self._format_exploration_data(exploration_result)
        logger.debug(f"Formatted exploration data: {len(exploration_data)} chars")

        # 2. Build prompt
        prompt = self._build_prompt(exploration_data)

        # 3. Call LLM
        try:
            response = self._call_llm(prompt)
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            return []

        # 4. Parse response
        tasks_data = self._parse_llm_response(response)

        # 5. Convert to SynthesizedTask objects
        tasks = []
        for i, task_data in enumerate(tasks_data, 1):
            try:
                task_id = f"task_{i}"
                name = task_data.get("name", f"Task {i}")
                description = task_data.get("description", "")
                category = task_data.get("category", "general")
                steps_text = task_data.get("steps", [])

                # Convert steps
                steps = []
                for j, step_text in enumerate(steps_text, 1):
                    if isinstance(step_text, str):
                        steps.append(TaskStep(
                            step_number=j,
                            description=step_text
                        ))
                    elif isinstance(step_text, dict):
                        steps.append(TaskStep(
                            step_number=j,
                            description=step_text.get("description", ""),
                            screen_id=step_text.get("screen_id"),
                            action_id=step_text.get("action_id")
                        ))

                task = SynthesizedTask(
                    task_id=task_id,
                    name=name,
                    description=description,
                    steps=steps,
                    category=category
                )
                tasks.append(task)
                logger.info(f"Synthesized task: {name}")

            except Exception as e:
                logger.warning(f"Failed to parse task {i}: {e}")
                continue

        logger.info(f"Successfully synthesized {len(tasks)} tasks")
        return tasks

    def save_tasks(self, tasks: List[SynthesizedTask], output_file: Path):
        """
        Save synthesized tasks to JSON file.

        Args:
            tasks: List of synthesized tasks
            output_file: Output file path
        """
        output_file.parent.mkdir(parents=True, exist_ok=True)

        data = {
            "tasks": [task.to_dict() for task in tasks],
            "metadata": {
                "total_tasks": len(tasks),
                "synthesizer": "LLMTaskSynthesizer",
                "llm_provider": self.llm_provider,
                "model": self.model
            }
        }

        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        logger.info(f"Saved {len(tasks)} tasks to {output_file}")

    def save_summary(self, tasks: List[SynthesizedTask], output_file: Path):
        """
        Save human-readable summary of tasks.

        Args:
            tasks: List of synthesized tasks
            output_file: Output file path
        """
        output_file.parent.mkdir(parents=True, exist_ok=True)

        lines = []
        lines.append("=" * 80)
        lines.append("LLM-BASED TASK SYNTHESIS SUMMARY")
        lines.append("=" * 80)
        lines.append(f"\nTotal Tasks: {len(tasks)}")
        lines.append(f"LLM Provider: {self.llm_provider}")
        lines.append(f"Model: {self.model}\n")

        # Group by category
        by_category = {}
        for task in tasks:
            cat = task.category
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(task)

        lines.append(f"Categories: {', '.join(by_category.keys())}\n")
        lines.append("=" * 80)

        for i, task in enumerate(tasks, 1):
            lines.append(f"\n{i}. {task.name}")
            lines.append(f"   Category: {task.category}")
            lines.append(f"   Description: {task.description}")
            lines.append(f"   Steps ({len(task.steps)}):")
            for step in task.steps:
                lines.append(f"      {step.step_number}. {step.description}")

        lines.append("\n" + "=" * 80)

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))

        logger.info(f"Saved summary to {output_file}")


# Convenience function for easy usage
def synthesize_tasks_with_llm(
    exploration_result: ExplorationResult,
    output_dir: Path,
    llm_provider: str = "anthropic",
    **kwargs
) -> List[SynthesizedTask]:
    """
    Convenience function to synthesize tasks with LLM.

    Args:
        exploration_result: Exploration result from Phase 1
        output_dir: Directory to save outputs
        llm_provider: "anthropic" or "openai"
        **kwargs: Additional arguments for LLMTaskSynthesizer

    Returns:
        List of synthesized tasks
    """
    synthesizer = LLMTaskSynthesizer(llm_provider=llm_provider, **kwargs)
    tasks = synthesizer.synthesize_tasks(exploration_result)

    # Save results
    output_dir = Path(output_dir)
    synthesizer.save_tasks(tasks, output_dir / "tasks_llm.json")
    synthesizer.save_summary(tasks, output_dir / "tasks_llm_summary.txt")

    return tasks
