#!/usr/bin/env python3
"""
Run Task Validation (Phase 3) on synthesized tasks.

Usage:
    python scripts/run_validation.py --tasks data/tasks/example.com/tasks_llm.json --url https://example.com
    python scripts/run_validation.py --input data/raw/example.com --url https://example.com --verbose
"""

import asyncio
import argparse
import logging
import sys
import json
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from exploration.task_validator import TaskValidator
from exploration.llm_task_synthesizer import SynthesizedTask, TaskStep
from envs.generic_env import GenericWebEnv
from exploration.storage import url_to_folder_name

# Setup logging
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def load_tasks_from_json(json_file: Path) -> list:
    """Load tasks from JSON file generated by Phase 2."""
    logger.info(f"Loading tasks from: {json_file}")

    with open(json_file, 'r') as f:
        data = json.load(f)

    tasks = []
    for task_data in data.get('tasks', []):
        steps = [
            TaskStep(
                step_number=step['step_number'],
                description=step['description'],
                screen_id=step.get('screen_id'),
                action_id=step.get('action_id')
            )
            for step in task_data.get('steps', [])
        ]

        task = SynthesizedTask(
            task_id=task_data['task_id'],
            name=task_data['name'],
            description=task_data['description'],
            steps=steps,
            confidence=task_data.get('confidence', 0.5),
            category=task_data.get('category', 'unknown')
        )
        tasks.append(task)

    logger.info(f"Loaded {len(tasks)} tasks")
    return tasks


async def run_validation(args):
    """Run Phase 3 Task Validation."""

    logger.info("\n" + "=" * 60)
    logger.info("PHASE 3: Task Validation (LLM Executes Tasks)")
    logger.info("=" * 60)
    logger.info(f"URL: {args.url}")
    logger.info(f"Tasks: {args.tasks}")
    logger.info("=" * 60)

    # Load tasks
    tasks = load_tasks_from_json(Path(args.tasks))

    # Create environment
    logger.info("\nInitializing web environment...")
    env = GenericWebEnv(
        start_url=args.url,
        headless=args.headless,
        max_steps=args.max_steps
    )

    try:
        # Create validator
        validator = TaskValidator(
            env=env,
            max_steps_per_task=args.max_steps_per_task,
            timeout_per_task=args.timeout_per_task
        )

        # Run validation
        report = await validator.validate_tasks(
            tasks=tasks,
            save_validated=True,
            output_dir=Path(args.tasks).parent / "validation"
        )

        # Print summary
        logger.info("\n" + "=" * 60)
        logger.info("VALIDATION SUMMARY")
        logger.info("=" * 60)
        logger.info(f"Total tasks: {report.total_tasks}")
        logger.info(f"✅ Validated: {report.validated_tasks} ({report.success_rate*100:.1f}%)")
        logger.info(f"❌ Failed: {report.failed_tasks} ({(1-report.success_rate)*100:.1f}%)")
        logger.info("=" * 60)

        return 0

    except Exception as e:
        logger.error(f"Validation failed: {e}", exc_info=True)
        return 1

    finally:
        try:
            await env.close()
        except Exception as e:
            logger.error(f"Error closing environment: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Run Task Validation (Phase 3) on synthesized tasks"
    )

    parser.add_argument(
        "--tasks",
        required=True,
        help="Path to tasks JSON file (e.g., data/tasks/example.com/tasks_llm.json)"
    )

    parser.add_argument(
        "--url",
        required=True,
        help="Target URL (must match the domain where tasks were explored)"
    )

    parser.add_argument(
        "--max-steps-per-task",
        type=int,
        default=20,
        help="Maximum steps to attempt per task (default: 20)"
    )

    parser.add_argument(
        "--timeout-per-task",
        type=int,
        default=60,
        help="Timeout per task in seconds (default: 60)"
    )

    parser.add_argument(
        "--max-steps",
        type=int,
        default=50,
        help="Maximum steps per episode (default: 50)"
    )

    parser.add_argument(
        "--headless",
        action="store_true",
        default=True,
        help="Run browser in headless mode (default: True)"
    )

    parser.add_argument(
        "--no-headless",
        action="store_false",
        dest="headless",
        help="Run browser in visible mode (for debugging)"
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose logging (DEBUG level)"
    )

    args = parser.parse_args()

    # Run validation
    exit_code = asyncio.run(run_validation(args))
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
